version: 2
jobs:
  build:
    docker:
      - image: dataknightllc/cibuilder:stable
    working_directory: /build

    environment:
      - REPO_NAME: dataknightllc/ejbca
      - REPO_TAG: latest
      
    steps:
      - checkout

      - setup_remote_docker:
          reusable: true

      - run:
          name: Build container image
          command: |
            set -x
            if [[ $(git log -n1 --pretty=%B | grep "^circleci:" | grep "nobuild") == "" ]]; then
              docker-compose build
            fi

      - run:
          name: Add image tags
          command: |
            set -x
            if [[ $(git log -n1 --pretty=%B | grep "^circleci:" | grep "notag") == "" ]]; then
              if [[ $(git log -n1 --pretty=%B | grep "^Release ") != "" ]]; then
                RELEASE=$(git log -n1 --pretty=%B | grep "^Release ");
                IFS=' ' read r1 VERSION r2 REV STATUS <<< "${RELEASE}";
                IFS='.' read MAJOR MINOR BUILD <<< "${VERSION}";
                docker tag ${REPO_NAME}:${REPO_TAG} ${REPO_NAME}:${MAJOR}.${MINOR}.${BUILD}-r${REV};
                docker tag ${REPO_NAME}:${REPO_TAG} ${REPO_NAME}:${MAJOR}.${MINOR}.${BUILD};
                if [[ "${STATUS}" == "(stable)" ]]; then
                  docker tag ${REPO_NAME}:${REPO_TAG} ${REPO_NAME}:${MAJOR}.${MINOR};
                  docker tag ${REPO_NAME}:${REPO_TAG} ${REPO_NAME}:${MAJOR};
                  docker tag ${REPO_NAME}:${REPO_TAG} ${REPO_NAME}:stable;
                fi;
              fi
            fi

      - run:
          name: Push image to Docker registry
          command: |
            set -x
            if [[ $(git log -n1 --pretty=%B | grep "^circleci:" | grep "nopush") == "" ]]; then
              docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
              docker push ${REPO_NAME}
            fi
